### ISSUE TITLE
How exactly does retrieving username work

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/admincom#206]
Hi 20C,

I'm referring to https://peeringdb.com/username-retrieve. A user reported that he used this tool with an email address not in the system. However peering@his_dom.in was in the system  and he was returned the username associated with this email address.

See DeskPRO ticket 20972

TIA
Arnold

**Comment by vegu** [comment]
@arnoldnipper The system will look for the email address entered and send a link to page containing all attached usernames to it. (if the email exists)

The behaviour described by the user seems extremely unlikely and there is no obvious logic in the code that would cause something like this.

**Comment by vegu** [comment]
@arnoldnipper did the link he got emailed contain any usernames ?

**Comment by vegu** [comment]
@arnoldnipper  I read the DeskPRO ticket - to answer one of the questions raised there: the process will not do any partial matching of emails, the email needs to be exact. If it doesnt find it it should not send anything.

I am not sure how the connection between a non existent mail and an existing mail would have been made as the user describes it. 

However I was able to reproduce a version of this bug by using a non existent email address, which got sent an email, but the resulting link contained no usernames (since the email does not exist in pdb).

**Comment by arnoldnipper** [comment]
@vegu thanks for teh swift response. Do you please open an issue in /peeringdb. I will close the issue here

**Comment by vegu** [comment]
@arnoldnipper done - https://github.com/peeringdb/peeringdb/issues/365
