### ISSUE TITLE
De-board Luisa Fernanda Villa y Battenberg from AC

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/admincom#219]
[x] deskpro
[x] downgrade peeringdb user
[ ] remove from admincom mailing list
[x] remove from admin page in PDB deck
[ ] award plaque sent

07/2017 - 10/2018

Luisa Fernanda Villa y Battenberg
Hattinger Stieg 13a
22419 Hamburg
Germany

**Comment by ghankins** [comment]
[x] remove from admin page in PDB deck

**Comment by ccaputo** [comment]
[x] deskpro
[x] downgrade peeringdb user
[x] remove from admincom mailing list
[x] remove from admin page in PDB deck
[ ] award plaque sent

07/2017 - 10/2018

Luisa Fernanda Villa y Battenberg
Hattinger Stieg 13a
22419 Hamburg
Germany

@arnoldnipper : should Luisa's G-Suite login be kept open?  It wasn't in her checklist.

**Comment by ccaputo** [comment]
[x] deskpro
[x] downgrade peeringdb user
[x] remove from admincom mailing list
[*] close peeringdb.com email address
[x] remove from admin page in PDB deck
[ ] award plaque sent

07/2017 - 10/2018

Luisa Fernanda Villa y Battenberg
Hattinger Stieg 13a
22419 Hamburg
Germany

*: 8 months since last sign-in, so suspended.  G-Suite deletion scheduled for 1 month from today on Caputo's calendar.

**Comment by arnoldnipper** [comment]
> should Luisa's G-Suite login be kept open? It wasn't in her checklist

no, @ccaputo

**Comment by arnoldnipper** [comment]
[x] deskpro
[x] downgrade peeringdb user
[x] remove from admincom mailing list
[*] close peeringdb.com email address
[x] remove from admin page in PDB deck
[x] award plaque sent
