### ISSUE TITLE
Merge duplicate IXP LAN 876 > 1511

### ISSUE THREAD

**Issue by NETRAVNEN** [peeringdb/admincom#78]
Could you merge data from:
- deleted IX LAN 876,
- to IX LAN 1511 ?

Both IX LANs belongs RED-IX.
Org-admin deleted ixlan 876 by mistake and wants to recover the data. Org-admin created ixlan 1511 before writing to pdb.

**Comment by arnoldnipper** [comment]
Alas we dont have the command line tools to merge single ixlans at this point.

However seeing as the ixlan in question only had a handful of netixlans i went ahead and recreated manually. Please have the ix check on their end that it all looks in order.

These are the netixlans that were recreated on the new ixlan:

+--------------+------------------------+--------+------------+-------+------------+
| ipaddr4      | ipaddr6                | asn    | network_id | speed | is_rs_peer |
+--------------+------------------------+--------+------------+-------+------------+
| 185.1.13.24  | 2001:7f8:78::5:923:1   |  50923 |       7238 |  2000 |         1 |
| 185.1.13.38  | NULL                   |  57629 |       4597 | 10000 |         1 |
| 185.1.13.55  | NULL                   |  58067 |      11818 |  2000 |         1 |
| 185.1.13.54  | 2001:7f8:78::1:3238:1  |  13238 |       1751 | 10000 |         1 |
| 185.1.13.32  | NULL                   |  44347 |      14842 |  1000 |         1 |
| 185.1.13.50  | 2001:7f8:78::20:2806:1 | 202806 |      15124 |     0 |         0 |
+--------------+------------------------+--------+------------+-------+------------+

Note that i had to give the '185.1.13.50' netixlan a speed value in order to re-create it, i set it to 1000.
